note1.pdf: note1.dvi
	dvipdfmx note1.dvi
note1.dvi: note1.tex fig1_1.eps fig1_2.eps fig1_3.eps fig1_4.eps fig1_4_1.eps fig1_4_2.eps fig1_5.eps fig1_6.eps fig1_7.eps fig1_8.eps
	platex note1.tex

fig1_1.eps: fig1_1.svgz
	inkscape -z -f fig1_1.svgz -E fig1_1.eps 
fig1_2.eps: fig1_2.svgz
	inkscape -z -f fig1_2.svgz -E fig1_2.eps 
fig1_3.eps: fig1_3.svgz
	inkscape -z -f fig1_3.svgz -E fig1_3.eps 
fig1_4.eps: fig1_4.svgz
	inkscape -z -f fig1_4.svgz -E fig1_4.eps 
fig1_4_1.eps: fig1_4_1.svgz
	inkscape -z -f fig1_4_1.svgz -E fig1_4_1.eps 
fig1_4_2.eps: fig1_4_2.svgz
	inkscape -z -f fig1_4_2.svgz -E fig1_4_2.eps 
fig1_5.eps: fig1_5.svgz
	inkscape -z -f fig1_5.svgz -E fig1_5.eps 
fig1_6.eps: fig1_6.svgz
	inkscape -z -f fig1_6.svgz -E fig1_6.eps 
fig1_7.eps: fig1_7.svgz
	inkscape -z -f fig1_7.svgz -E fig1_7.eps 
fig1_8.eps: fig1_8.svgz
	inkscape -z -f fig1_8.svgz -E fig1_8.eps 


